const cfg=window.__GUITARRUN_CONFIG__||{};
const API=cfg.apiBase||'http://127.0.0.1:4100';
const TOKEN_KEY='guitarrun-session-token';
let token=localStorage.getItem(TOKEN_KEY),user=null,practiceSessionId=null,lastVerifiedHitAt=0,pendingActiveMs=0;
const $=id=>document.getElementById(id);
const t=(key,fallback=key)=>window.__FRET_T?.(key)||fallback;
const authHeaders=()=>({Authorization:`Bearer ${token}`,'Content-Type':'application/json'});
const formatTime=seconds=>{const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=Math.floor(seconds%60);return h?`${h}h ${m}m`:m?`${m}m`:`${s}s`};
const imageUrl=value=>!value?'/brand/guitarrun-icon.svg':/^https?:\/\//.test(value)?value:`${API}${value}`;
async function api(path,options={}){const response=await fetch(`${API}${path}`,options);if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||`HTTP_${response.status}`);return response.status===204?null:response.json()}
function openProfile(){ $('profileModal').classList.add('open');$('profileModal').setAttribute('aria-hidden','false') }
function closeProfile(){ $('profileModal').classList.remove('open');$('profileModal').setAttribute('aria-hidden','true') }
function renderUser(){const signedIn=!!user;$('signedOutProfile').hidden=signedIn;$('signedInProfile').hidden=!signedIn;$('profileLabel').textContent=signedIn?user.displayName:'เข้าสู่ระบบ';$('profileAvatar').textContent=signedIn?user.displayName.slice(0,2).toUpperCase():'GR';if(!signedIn)return;$('profileName').textContent=user.displayName;$('profileEmail').textContent=user.email||'';$('profilePracticeTime').textContent=formatTime(user.totalPracticeSeconds);$('profileNotes').textContent=Number(user.totalNotesPlayed).toLocaleString();$('profileBestCombo').textContent=`${user.bestCombo}×`;$('profileImage').src=imageUrl(user.profileImageUrl)}
async function loadMe(){if(!token)return renderUser();try{user=(await api('/auth/me',{headers:authHeaders()})).user}catch{token=null;localStorage.removeItem(TOKEN_KEY)}renderUser()}
function initGoogle(){if(!cfg.googleClientId){$('googleSetupHint').textContent='เพิ่ม NUXT_PUBLIC_GOOGLE_CLIENT_ID เพื่อเปิด Google Login';return}if(!window.google?.accounts?.id)return setTimeout(initGoogle,400);window.google.accounts.id.initialize({client_id:cfg.googleClientId,callback:async({credential})=>{const result=await api('/auth/google',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idToken:credential})});token=result.session.token;user=result.user;localStorage.setItem(TOKEN_KEY,token);renderUser();loadLeaderboard()}});window.google.accounts.id.renderButton($('googleSignIn'),{theme:'filled_black',size:'large',shape:'pill',text:'continue_with',width:300})}
async function loadLeaderboard(){try{const data=await api('/leaderboard?limit=50'),rows=data.leaderboard||[],topTime=Math.max(rows[0]?.totalPracticeSeconds||0,1),totalTime=rows.reduce((sum,row)=>sum+row.totalPracticeSeconds,0);$('leaderboardPlayers').textContent=rows.length.toLocaleString();$('leaderboardTotalTime').textContent=formatTime(totalTime);$('leaderboardChampion').textContent=rows[0]?.displayName||'—';const podiumOrder=[rows[1],rows[0],rows[2]].filter(Boolean);$('leaderboardPodium').innerHTML=podiumOrder.length?podiumOrder.map(row=>`<article class="podium-card rank-${row.rank} ${user?.id===row.id?'is-me':''}"><span class="podium-place">${row.rank===1?'♛':'#'}${row.rank}</span><div class="podium-avatar"><img src="${imageUrl(row.profileImageUrl)}" alt=""><i>${row.rank}</i></div><strong>${escapeHtml(row.displayName)}</strong><em>${formatTime(row.totalPracticeSeconds)}</em><div class="podium-stats"><span><b>${row.totalNotesPlayed.toLocaleString()}</b> ${t('notes')}</span><span><b>${row.bestCombo}×</b> ${t('combo')}</span><span><b>${row.bestScore.toLocaleString()}</b> ${t('points')}</span></div>${user?.id===row.id?`<small>${t('your_rank')}</small>`:''}</article>`).join(''):`<div class="leaderboard-empty"><b>${t('empty_title')}</b><span>${t('empty_desc')}</span></div>`;$('globalLeaderboard').innerHTML=rows.length?rows.map(row=>`<article class="leaderboard-row ${user?.id===row.id?'is-me':''}"><b class="leaderboard-rank">#${row.rank}</b><div class="leaderboard-player"><img src="${imageUrl(row.profileImageUrl)}" alt=""><div><strong>${escapeHtml(row.displayName)}${user?.id===row.id?`<small>${t('you')}</small>`:''}</strong><span>${row.totalNotesPlayed.toLocaleString()} ${t('notes').toUpperCase()} · ${t('combo').toUpperCase()} ${row.bestCombo}× · ${row.bestScore.toLocaleString()} ${t('points').toUpperCase()}</span></div></div><div class="leaderboard-progress"><i style="width:${Math.max(4,Math.round(row.totalPracticeSeconds/topTime*100))}%"></i></div><em>${formatTime(row.totalPracticeSeconds)}</em></article>`).join(''):`<div class="leaderboard-loading">${t('no_ranking')}</div>`}catch{$('leaderboardPodium').innerHTML='';$('globalLeaderboard').innerHTML=`<div class="leaderboard-loading">${t('ranking_unavailable')}</div>`}}
const escapeHtml=value=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function startTrackedPractice(event){if(!token)return;try{const detail=event.detail||{};const result=await api('/practice/start',{method:'POST',headers:authHeaders(),body:JSON.stringify({scaleKey:detail.key,scaleName:detail.scale,patternName:detail.pattern})});practiceSessionId=result.session.id;lastVerifiedHitAt=0;pendingActiveMs=0}catch{}}
async function trackVerifiedHit(event){if(!token||!practiceSessionId)return;const now=Date.now();let activeSeconds=0;if(lastVerifiedHitAt){const gapMs=now-lastVerifiedHitAt;if(gapMs<=300000){pendingActiveMs+=gapMs;activeSeconds=Math.floor(pendingActiveMs/1000);pendingActiveMs-=activeSeconds*1000}}lastVerifiedHitAt=now;const detail=event.detail||{};try{await api(`/practice/${practiceSessionId}/activity`,{method:'POST',headers:authHeaders(),body:JSON.stringify({notesPlayed:1,activeSeconds,score:detail.score||0,maxCombo:detail.combo||0})})}catch{}}
async function endTrackedPractice(){if(!token||!practiceSessionId)return;const id=practiceSessionId;practiceSessionId=null;await api(`/practice/${id}/end`,{method:'POST',headers:authHeaders()}).catch(()=>{});loadMe();loadLeaderboard()}
$('profileButton').addEventListener('click',openProfile);$('profileClose').addEventListener('click',closeProfile);$('profileModal').addEventListener('click',event=>{if(event.target===$('profileModal'))closeProfile()});$('logoutButton').addEventListener('click',async()=>{await api('/auth/logout',{method:'POST',headers:authHeaders()}).catch(()=>{});token=null;user=null;localStorage.removeItem(TOKEN_KEY);renderUser()});$('profileImageInput').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file||!token)return;const body=new FormData();body.append('image',file);const result=await api('/profile/image',{method:'POST',headers:{Authorization:`Bearer ${token}`},body});user=result.user;renderUser();loadLeaderboard()});
window.addEventListener('guitarrun-practice-start',startTrackedPractice);window.addEventListener('guitarrun-verified-hit',trackVerifiedHit);window.addEventListener('guitarrun-practice-end',endTrackedPractice);window.addEventListener('fret-language-change',loadLeaderboard);window.addEventListener('beforeunload',()=>{if(token&&practiceSessionId)fetch(`${API}/practice/${practiceSessionId}/end`,{method:'POST',headers:authHeaders(),keepalive:true}).catch(()=>{})});
loadMe();loadLeaderboard();initGoogle();
