const cfg=window.__GUITARRUN_CONFIG__||{};
const rawApiBase=String(cfg.apiBase||'http://127.0.0.1:4100').trim();
const API=(/^https?:\/\//i.test(rawApiBase)
  ? rawApiBase
  : /^(localhost|127\.0\.0\.1)(:\d+)?(\/|$)/i.test(rawApiBase.replace(/^\/+/,''))
    ? `http://${rawApiBase.replace(/^\/+/, '')}`
    : `https://${rawApiBase.replace(/^\/+/, '')}`
).replace(/\/+$/,'');
const apiUrl=path=>`${API}/${String(path).replace(/^\/+/, '')}`;
if(import.meta.dev)console.info(`[GuitarRun] API base URL: ${API}`);
const TOKEN_KEY='guitarrun-session-token';
let token=localStorage.getItem(TOKEN_KEY),user=null,practiceSessionId=null,lastVerifiedHitAt=0,pendingActiveMs=0;
let googleLocale='',googleLoadPromise=null;
const $=id=>document.getElementById(id);
const t=(key,vars)=>window.__FRET_T?.(key,vars)||key;
const trackAnalytics=(event,details={})=>{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event,...details})};
const authHeaders=()=>({Authorization:`Bearer ${token}`,'Content-Type':'application/json'});
const formatTime=seconds=>{const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=Math.floor(seconds%60);return h?`${h}h ${m}m`:m?`${m}m`:`${s}s`};
const imageUrl=value=>!value?'/brand/guitarrun-icon.svg':/^https?:\/\//.test(value)?value:`${API}${value}`;
const localeCountries={th:'TH',en:'US',zh:'CN',ja:'JP',ko:'KR',es:'ES'};
const countryCodes=['TH','US','GB','CN','JP','KR','SG','MY','ID','PH','VN','LA','KH','MM','IN','AU','NZ','CA','MX','BR','AR','ES','FR','DE','IT','NL','SE','NO','DK','FI','CH','AT','BE','IE','PT','PL','CZ','GR','TR','SA','AE','ZA'];
const flagEmoji=code=>code&&/^[A-Z]{2}$/.test(code)?String.fromCodePoint(...[...code].map(char=>127397+char.charCodeAt(0))):'🌐';
const countryLabel=code=>{if(!code)return t('country_unknown');try{return new Intl.DisplayNames([document.documentElement.lang||'en'],{type:'region'}).of(code)||code}catch{return code}};
const renderCountryOptions=()=>{const select=$('profileCountry'),selected=select.value||user?.countryCode||'';select.innerHTML=`<option value="">${flagEmoji()} ${t('select_country')}</option>`+countryCodes.map(code=>`<option value="${code}">${flagEmoji(code)} ${escapeHtml(countryLabel(code))}</option>`).join('');select.value=selected};
const practiceLabel=session=>session.patternName||[session.scaleKey,session.scaleName].filter(Boolean).join(' · ');
const practiceTags=row=>{const practices=(row.recentPractices||[]).map(practiceLabel).filter(Boolean);return practices.length?practices.map(label=>`<span>${escapeHtml(label)}</span>`).join(''):`<span class="empty">${t('practice_unknown')}</span>`};
async function api(path,options={}){const response=await fetch(apiUrl(path),options);if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||`HTTP_${response.status}`);return response.status===204?null:response.json()}
function openProfile(){ $('profileModal').classList.add('open');$('profileModal').setAttribute('aria-hidden','false') }
function closeProfile(){ $('profileModal').classList.remove('open');$('profileModal').setAttribute('aria-hidden','true') }
function renderUser(){const signedIn=!!user;$('signedOutProfile').hidden=signedIn;$('signedInProfile').hidden=!signedIn;$('profileLabel').textContent=signedIn?user.displayName:t('sign_in');$('profileAvatar').textContent=signedIn?user.displayName.slice(0,2).toUpperCase():'GR';if(!signedIn)return;$('profileName').textContent=user.displayName;$('profileEmail').textContent=user.email||'';$('profilePracticeTime').textContent=formatTime(user.totalPracticeSeconds);$('profileNotes').textContent=Number(user.totalNotesPlayed).toLocaleString();$('profileBestCombo').textContent=`${user.bestCombo}×`;$('profileImage').src=imageUrl(user.profileImageUrl);renderCountryOptions();$('profileCountry').value=user.countryCode||''}
async function loadMe(){if(!token)return renderUser();try{user=(await api('/auth/me',{headers:authHeaders()})).user}catch{token=null;localStorage.removeItem(TOKEN_KEY)}renderUser()}
function loadGoogle(locale){if(window.google?.accounts?.id&&googleLocale===locale)return Promise.resolve();document.querySelector('script[data-guitarrun-google]')?.remove();try{delete window.google}catch{}googleLocale=locale;googleLoadPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.dataset.guitarrunGoogle='';script.src=`https://accounts.google.com/gsi/client?hl=${encodeURIComponent(locale)}`;script.async=true;script.onload=resolve;script.onerror=reject;document.head.appendChild(script)});return googleLoadPromise}
async function initGoogle(){if(!cfg.googleClientId){$('googleSetupHint').textContent=t('google_login_setup');return}const locale=document.documentElement.lang||'en';$('googleSignIn').replaceChildren();try{await loadGoogle(locale)}catch{$('googleSetupHint').textContent=t('audio_connection_failed');return}window.google.accounts.id.initialize({client_id:cfg.googleClientId,callback:async({credential})=>{const result=await api('/auth/google',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idToken:credential})});token=result.session.token;user=result.user;localStorage.setItem(TOKEN_KEY,token);trackAnalytics('login',{method:'google'});renderUser();loadLeaderboard()}});window.google.accounts.id.renderButton($('googleSignIn'),{theme:'filled_black',size:'large',shape:'pill',text:'continue_with',width:300,locale})}
async function loadLeaderboard(){
  try{
    const data=await api('/leaderboard?limit=50'),rows=data.leaderboard||[],topTime=Math.max(rows[0]?.totalPracticeSeconds||0,1),totalTime=rows.reduce((sum,row)=>sum+row.totalPracticeSeconds,0);
    $('leaderboardPlayers').textContent=rows.length.toLocaleString();$('leaderboardTotalTime').textContent=formatTime(totalTime);$('leaderboardChampion').textContent=rows[0]?.displayName||'—';
    const podiumOrder=[rows[1],rows[0],rows[2]].filter(Boolean);
    $('leaderboardPodium').innerHTML=podiumOrder.length?podiumOrder.map(row=>`<article class="podium-card rank-${row.rank} ${user?.id===row.id?'is-me':''}"><span class="podium-place">${row.rank===1?'♛':'#'}${row.rank}</span><div class="podium-avatar"><img src="${imageUrl(row.profileImageUrl)}" alt=""><i>${row.rank}</i></div><strong>${escapeHtml(row.displayName)}</strong><div class="player-country"><b>${flagEmoji(row.countryCode)}</b><span>${escapeHtml(countryLabel(row.countryCode))}</span></div><em>${formatTime(row.totalPracticeSeconds)}</em><div class="practice-tags">${practiceTags(row)}</div><div class="podium-stats"><span><b>${row.totalNotesPlayed.toLocaleString()}</b> ${t('notes')}</span><span><b>${row.bestCombo}×</b> ${t('combo')}</span><span><b>${row.bestScore.toLocaleString()}</b> ${t('points')}</span></div>${user?.id===row.id?`<small>${t('your_rank')}</small>`:''}</article>`).join(''):`<div class="leaderboard-empty"><b>${t('empty_title')}</b><span>${t('empty_desc')}</span></div>`;
    $('globalLeaderboard').innerHTML=rows.length?rows.map(row=>`<article class="leaderboard-row ${user?.id===row.id?'is-me':''}"><b class="leaderboard-rank">#${row.rank}</b><div class="leaderboard-player"><img src="${imageUrl(row.profileImageUrl)}" alt=""><div><strong>${escapeHtml(row.displayName)}${user?.id===row.id?`<small>${t('you')}</small>`:''}</strong><span class="player-country"><b>${flagEmoji(row.countryCode)}</b>${escapeHtml(countryLabel(row.countryCode))}</span><div class="practice-tags">${practiceTags(row)}</div><span>${row.totalNotesPlayed.toLocaleString()} ${t('notes').toUpperCase()} · ${t('combo').toUpperCase()} ${row.bestCombo}× · ${row.bestScore.toLocaleString()} ${t('points').toUpperCase()}</span></div></div><div class="leaderboard-progress"><i style="width:${Math.max(4,Math.round(row.totalPracticeSeconds/topTime*100))}%"></i></div><em>${formatTime(row.totalPracticeSeconds)}</em></article>`).join(''):`<div class="leaderboard-loading">${t('no_ranking')}</div>`;
  }catch{$('leaderboardPodium').innerHTML='';$('globalLeaderboard').innerHTML=`<div class="leaderboard-loading">${t('ranking_unavailable')}</div>`}
}
const escapeHtml=value=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function startTrackedPractice(event){if(!token)return;try{const detail=event.detail||{},countryCode=localeCountries[document.documentElement.lang]||localeCountries[(navigator.language||'').split('-')[0]];const result=await api('/practice/start',{method:'POST',headers:authHeaders(),body:JSON.stringify({scaleKey:detail.key,scaleName:detail.scale,patternName:detail.pattern,countryCode})});practiceSessionId=result.session.id;lastVerifiedHitAt=0;pendingActiveMs=0}catch{}}
async function trackVerifiedHit(event){if(!token||!practiceSessionId)return;const now=Date.now();let activeSeconds=0;if(lastVerifiedHitAt){const gapMs=now-lastVerifiedHitAt;if(gapMs<=300000){pendingActiveMs+=gapMs;activeSeconds=Math.floor(pendingActiveMs/1000);pendingActiveMs-=activeSeconds*1000}}lastVerifiedHitAt=now;const detail=event.detail||{};try{await api(`/practice/${practiceSessionId}/activity`,{method:'POST',headers:authHeaders(),body:JSON.stringify({notesPlayed:1,activeSeconds,score:detail.score||0,maxCombo:detail.combo||0})})}catch{}}
async function endTrackedPractice(){if(!token||!practiceSessionId)return;const id=practiceSessionId;practiceSessionId=null;await api(`/practice/${id}/end`,{method:'POST',headers:authHeaders()}).catch(()=>{});loadMe();loadLeaderboard()}
$('profileButton').addEventListener('click',openProfile);$('profileClose').addEventListener('click',closeProfile);$('profileModal').addEventListener('click',event=>{if(event.target===$('profileModal'))closeProfile()});$('logoutButton').addEventListener('click',async()=>{await api('/auth/logout',{method:'POST',headers:authHeaders()}).catch(()=>{});token=null;user=null;localStorage.removeItem(TOKEN_KEY);renderUser()});$('profileImageInput').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file||!token)return;const body=new FormData();body.append('image',file);const result=await api('/profile/image',{method:'POST',headers:{Authorization:`Bearer ${token}`},body});user=result.user;renderUser();loadLeaderboard()});
$('profileCountry').addEventListener('change',async event=>{const countryCode=event.target.value;if(!countryCode||!token)return;event.target.disabled=true;try{const result=await api('/profile/country',{method:'PATCH',headers:authHeaders(),body:JSON.stringify({countryCode})});user=result.user;renderUser();loadLeaderboard()}catch{event.target.value=user?.countryCode||''}finally{event.target.disabled=false}});
window.addEventListener('guitarrun-practice-start',startTrackedPractice);window.addEventListener('guitarrun-verified-hit',trackVerifiedHit);window.addEventListener('guitarrun-practice-end',endTrackedPractice);window.addEventListener('fret-language-change',()=>{renderUser();renderCountryOptions();loadLeaderboard();initGoogle()});window.addEventListener('beforeunload',()=>{if(token&&practiceSessionId)fetch(apiUrl(`/practice/${practiceSessionId}/end`),{method:'POST',headers:authHeaders(),keepalive:true}).catch(()=>{})});
renderCountryOptions();loadMe();loadLeaderboard();initGoogle();
